# Generated by Django 3.1.1 on 2023-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contactno',
        ),
    ]
